version: "3.0"

services:
  golang-server:
    build: .
    container_name: golang-server
    ports:
      - 5051:5051
    networks:
    - kong-quickstart-net
    restart: on-failure
  # Database
  # kong-database:
  #   image: postgres:latest
  #   container_name: kong-database
  #   environment:
  #     POSTGRES_DB: kong
  #     POSTGRES_USER: kong
  #     POSTGRES_PASSWORD: kong
  #   networks:
  #     - kong-net
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "kong"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: on-failure
  # # Kong
  # kong-gateway:
  #   image: kong/kong-gateway
  #   container_name: kong-gateway
  #   depends_on:
  #     kong-database:
  #       condition: service_healthy
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-db
  #     KONG_PG_USER: kong
  #     KONG_PG_PASSWORD: kong
  #     KONG_PG_DATABASE: kong
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #   networks: 
  #     - kong-net
  #   ports:
  #     - 8000:8000
  #     - 8001:8001
  #     - 8002:8002
  #   healthcheck:
  #     test: ["CMD", "kong", "health"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #   restart: on-failure